"""Builds src/mapdata.js (world coastline + rivers) from Natural Earth 50m GeoJSON (public domain, naturalearthdata.com).
Usage: python build_map.py land.json rivers.json
Coordinates: x = (lon + 180) * K, y = (90 - lat) * K, so a pin at (lat, lon) lands at the same spot on the map."""
import json
import sys
from pathlib import Path

K = 20
TOL_LAND, TOL_RIVER = 0.03, 0.04   # degrees


def rdp(pts, tol):
    if len(pts) < 3:
        return pts
    keep = [False] * len(pts)
    keep[0] = keep[-1] = True
    stack = [(0, len(pts) - 1)]
    while stack:
        a, b = stack.pop()
        (ax, ay), (bx, by) = pts[a], pts[b]
        dx, dy = bx - ax, by - ay
        n = dx * dx + dy * dy or 1e-12
        best, idx = 0, -1
        for i in range(a + 1, b):
            px, py = pts[i]
            t = max(0, min(1, ((px - ax) * dx + (py - ay) * dy) / n))
            d = (px - ax - t * dx) ** 2 + (py - ay - t * dy) ** 2
            if d > best:
                best, idx = d, i
        if best > tol * tol and idx > 0:
            keep[idx] = True
            stack += [(a, idx), (idx, b)]
    return [p for p, k in zip(pts, keep) if k]


def path(rings, tol, close):
    out = []
    for r in rings:
        s = rdp([(x, y) for x, y in r], tol)
        if len(s) < (4 if close else 2):
            continue
        out.append("M" + "L".join(f"{round((x + 180) * K)} {round((90 - y) * K)}" for x, y in s) + ("Z" if close else ""))
    return "".join(out)


def main(land_file, river_file):
    land, rivers = [], []
    for f in json.load(open(land_file, encoding="utf-8"))["features"]:
        g = f["geometry"]
        polys = g["coordinates"] if g["type"] == "MultiPolygon" else [g["coordinates"]]
        for poly in polys:
            land += poly
    for f in json.load(open(river_file, encoding="utf-8"))["features"]:
        if f["properties"].get("featurecla") != "River":
            continue
        g = f["geometry"]
        lines = g["coordinates"] if g["type"] == "MultiLineString" else [g["coordinates"]]
        rivers += lines
    out = Path(__file__).parent.parent / "src" / "mapdata.js"
    out.write_text("// Generated by tools/build_map.py from Natural Earth 50m (public domain). Do not edit.\n"
                   f"export const K = {K};\nexport const LAND = {json.dumps(path(land, TOL_LAND, True))};\n"
                   f"export const RIVERS = {json.dumps(path(rivers, TOL_RIVER, False))};\n", encoding="utf-8")
    print(out, out.stat().st_size // 1024, "KB")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
